---

x-containers-options: &x-containers-options
  restart: unless-stopped
  env_file:
    - .env
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

x-containers-healthcheck: &x-containers-healthcheck
  interval: 5s
  timeout: 3s
  retries: 5

services:
  munin-master:
    build:
      context: docker
      dockerfile: Dockerfile.munin
    image: munin:latest
    user: munin
    command: ["supercronic", "/etc/supercronic.conf"]
    <<: *x-containers-options
    healthcheck:
      <<: *x-containers-healthcheck
      test: ["CMD", "true"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./conf/supercronic.conf:/etc/supercronic.conf
      - ./conf/munin.conf:/etc/munin/munin.conf
      - munin_db:/var/lib/munin

  munin-node:
    build:
      context: docker
      dockerfile: Dockerfile.munin
    image: munin:latest
    user: root
    entrypoint: ""
    command: ["/bin/sh","-c","ln -sf /usr/lib/munin/plugins/memory /etc/munin/plugins; ln -sf /usr/lib/munin/plugins/cpuspeed /etc/munin/plugins; ln -sf /usr/lib/munin/plugins/cpu /etc/munin/plugins; /usr/sbin/munin-node"]
    <<: *x-containers-options
    healthcheck:
      <<: *x-containers-healthcheck
      test: ["CMD", "nc", "-z", "127.0.0.1","4949"]
    ports:
      - "4949:4949"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./conf/munin-node.conf:/etc/munin/munin-node.conf

  nginx:
    build:
      context: docker
      dockerfile: Dockerfile.nginx
    image: munin-nginx:latest
    depends_on:
      - munin-master
      - cgi-html
      - cgi-graph
    <<: *x-containers-options
    healthcheck:
      <<: *x-containers-healthcheck
      test: ["CMD", "nc", "-z", "127.0.0.1","80"]
    ports:
      - "8080:80"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf

  cgi-graph:
    build:
      context: docker
      dockerfile: Dockerfile.munin
    image: munin:latest
    user: munin
    command: ["spawn-fcgi","-n","-p 4970","-u 100","-g 101","/usr/share/webapps/munin/cgi/munin-cgi-graph"]
    depends_on:
      - munin-master
    <<: *x-containers-options
    healthcheck:
      <<: *x-containers-healthcheck
      test: ["CMD", "nc", "-z", "127.0.0.1","4970"]
    expose:
      - "4970"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - munin_db:/var/lib/munin

  cgi-html:
    build:
      context: docker
      dockerfile: Dockerfile.munin
    image: munin:latest
    user: munin
    command: ["spawn-fcgi","-n","-p 4980","-u 100","-g 101","/usr/share/webapps/munin/cgi/munin-cgi-html"]
    depends_on:
      - munin-master
    <<: *x-containers-options
    healthcheck:
      <<: *x-containers-healthcheck
      test: ["CMD", "nc", "-z", "127.0.0.1","4980"]
    expose:
      - "4980"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - munin_db:/var/lib/munin

volumes:
  munin_db:

